# Make sure to check your instance configuration before starting the server.
# Two instances of Rift using the same server-id will cause data persistence issues.
instance:
  proxy-id: 'NA'
  server-id: 'Hub-01'

# The interval (in seconds) in which this instance of Rift broadcasts updates to other Rift instances.
broadcast-update-interval: 3

# Prevents players from being able to join queues from this server
disable-queues: false

# Prevents default players from being able to join a queue via command
disable-queue-join-command: true

# Settings relating to the spoofing mechanic
spoof:
  enabled: false
  paused: false
  multiplier: 2.0 # The factor to multiply the real player count by
  min: 10
  max: 100
  buffer: 10
  interval: 20
  min-delay: 1000L
  max-delay: 3500L
  # Settings relating to making fake players look real
  realism:
    # Assigning ranks to fake players
    # rank id -> chance
    rank-assignment:
      junkieplus: 2.5
      junkie: 5.0
      bedrock: 5.0
      obsidian: 15.0
      emerald: 20.0
      diamond: 20.0
      gold: 25.0
      lapis: 30.0
      redstone: 50.0
    # Making fake players perform actions
    actions:
      - chance: 100.0
        command: "plot auto"
      - chance: 20.0
        command: "plot home"
      - chance: 20.0
        command: "warp crates"
      - chance: 20.0
        command: "warp lb"
      - chance: 20.0
        command: "warp a"
      - chance: 20.0
        command: "warp info"